package com.warriortech.resb.model

data class TblBillingRequest(
    var bill_no: String,
    var bill_date: String,
    var bill_create_time: String,
    var order_master_id: String,
    var voucher_id: Long,
    var staff_id: Long,
    var customer_id: Long,
    var order_amt: Double,
    var disc_amt: Double,
    var tax_amt: Double,
    var cess: Double,
    var cess_specific: Double,
    var delivery_amt: Double,
    var grand_total: Double,
    var round_off: Double,
    var rounded_amt: Double,
    var cash: Double,
    var card: Double,
    var upi: Double,
    var due: Double,
    var others: Double,
    var received_amt: Double,
    var pending_amt: Double,
    var change: Double,
    var note: String,
    var is_active: Long
)

data class TblBillingResponse(
    var bill_no: String,
    var bill_date: String,
    var bill_create_time: String,
    var order_master: TblOrderResponse,
    var voucher: TblVoucher,
    var staff: TblStaff,
    var customer: TblCustomer,
    var order_amt: Double,
    var disc_amt: Double,
    var tax_amt: Double,
    var cess: Double,
    var cess_specific: Double,
    var delivery_amt: Double,
    var grand_total: Double,
    var round_off: Double,
    var rounded_amt: Double,
    var cash: Double,
    var card: Double,
    var upi: Double,
    var due: Double,
    var others: Double,
    var received_amt: Double,
    var pending_amt: Double,
    var change: Double,
    var note: String,
    var is_active: Long
)

data class BillItem(
    val sn: Int,
    val itemName: String,
    val qty: Int,
    val price: Double,
    val basePrice: Double,
    val amount: Double,
    val taxPercent: Double,
    val taxAmount: Double,
    val sgstPercent: Double,
    val cgstPercent: Double,
    val igstPercent: Double,
    val cessPercent: Double,
    val sgst: Double,
    val cgst: Double,
    val igst: Double,
    val cess: Double,
    val cess_specific: Double,
)

data class Bill(
    val company_code: String,
    val billNo: String,
    val date: String,
    val time: String,
    val orderNo: String,
    val counter: String,
    val tableNo: String,
    val custName: String,
    val custNo: String,
    val custAddress: String,
    val custGstin: String,
    val items: List<BillItem>,
    val subtotal: Double,
    val deliveryCharge: Double,
    val discount: Double,
    val roundOff: Double,
    val total: Double,
    val paperWidth: Int = 48,
    val received_amt: Double,
    val pending_amt: Double
)