package com.warriortech.resb.model

data class GeneralSettings(
    var id: Int = 1,
    var company_name_font: Int,
    var address_font: Int,
    var is_tax: Boolean,
    var is_tax_included: Boolean,
    var is_round_off: Boolean,
    var is_allowed_disc: Boolean,
    var disc_by: Int,
    var disc_amt: Double,
    var is_tendered: Boolean,
    var is_gst_summary: Boolean,
    var is_receipt: Boolean,
    var is_kot: Boolean,
    var is_logo: Boolean,
    var logo_path: String,
    var is_cess: Boolean,
    var is_delivery_charge: Boolean,
    var is_table_allowed: Boolean,
    var is_waiter_allowed: Boolean,
    var menu_show_in_time: Boolean,
    var tamil_receipt_print: Boolean,
    var logo_size: Long,
    var is_split_gst: Boolean,
    var bill_footer: String,
    var is_company_show: Boolean,
    var is_qr_show: Boolean,
    var remark1: String,
    var remark2: String,
    var business_date: String,
    var is_accounts: Boolean,
    var is_inventory: Boolean
)